// <auto-generated />
namespace SmartSSO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitralCreate15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitralCreate15));
        
        string IMigrationMetadata.Id
        {
            get { return "201801081516214_InitralCreate15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
